title: Abdul Jameel
logo: 4 Github.png
description: text below image
theme: jekyll-theme-minimal
description: >-
  Aspiring Accounting Professional | Power BI | Tableau  | Excel | SQL
  Helping businesses make data-driven decisions with clear, compelling dashboards.
ReadMe

# ğŸ‘‹ Hi, I'm Abdul Jameel 
Aspiring Accounting Professional | Transforming Insights into Impact  

<!--Section 1: Introduction-->

## ğŸŒŸ About Me  
I'm an aspiring Accounting Professional, with 4 years of GCC experience. passionate about finance and accounts.
Proficient in overseeing accounts payable, month-end closing processes, and preparing comprehensive financial statements.  
Skilled in **Power BI**, **Excel (advanced)**, **DAX**, and **SQL**, enabling the creation of interactive dashboards and actionable insights.
I build dynamic dashboards, streamline reporting workflows.  
I bring a versatile approach to data storytelling. 
ğŸš€Let's focus on crafting powerful stories from data!
---

## ğŸ“ Education  
- **Data Analytics**  
  *Rows and Columns â€¢ Calicut, Kerala, India â€¢ 06/2025 - 09/2025*  
  
  - **Masters in Business Administration - finance**  
  *Maulana Azad National Urdu University â€¢ Hyderabad, India*  

  - **MBachelor of Commerce**  
  *University of Calicut â€¢ Kerala, India*  

---

## ğŸ’¼ Work Experience  


---

## ğŸ“Š Projects  


## ğŸ§  Tools & Skills  
![Power BI](https://img.shields.io/badge/-Power%20BI-239120?logo=Power-BI&logoColor=white) 
![MS Excel](https://img.shields.io/badge/-Excel-217346?logo=Microsoft-Excel&logoColor=white) 
![SQL](https://img.shields.io/badge/-SQL-CC2927?logo=MySQL&logoColor=white) 
![Tableau](https://img.shields.io/badge/-Tableau-E97627?logo=Tableau&logoColor=white) 
![Python](https://img.shields.io/badge/-Python-3776AB?logo=Python&logoColor=white)  

---

## ğŸ¯ Interests  
- ğŸ“Š Dashboard Design  
- âš½ Badminton & Football  
- ğŸ¬ Reading & ğŸ’ Cooking  

---

## ğŸ“« Contact Details  
*Letâ€™s connect and see how we can make a difference together!*  

<table>
  <tbody>
    <tr>
      <td>ğŸ“§</td>
      <td><a href="mailto:jamimasket@gmail.com">jamimasket@gmail.com</a></td>
    </tr>
    <tr>
      <td>ğŸ“</td>
      <td>(+91) 984-694-4044</td>
    </tr>
    <tr>
      <td>ğŸ“</td>
      <td>Malappuram, Kerala</td>
    </tr>
    <tr>
     
